# Generated by Django 4.2 on 2025-06-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="База знаний", max_length=255)),
                (
                    "content",
                    models.TextField(help_text="Вставьте сюда текст базы знаний"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="KnowledgeEntry",
        ),
    ]
