# Generated by Django 4.2 on 2025-06-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_knowledgeblock_delete_knowledgeentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assistant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
