# Generated by Django 4.2 on 2025-06-20 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_assistant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assistant_telegram_id",
                    models.CharField(max_length=100, unique=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bot.client"
                    ),
                ),
            ],
        ),
    ]
